<?php
	$name=$_POST['nom'];
	$ip="localhost";
	//$ip="rt-projet.pu-pm.univ-fcomte.fr";
	//$ip="127.0.0.2";
	$user="jbettig";
	$dbname="jbettig_01";
	$pass="Benlechien";
	$ville=$json=$climat="test";
?>
